import { QuestionDefinition, RespondentType } from "@/types/survey";

export const PERSONA_GATE_QUESTION: QuestionDefinition = {
  id: "gate",
  stepNumber: 0,
  sectionCode: "GATE",
  sectionName: "Respondent Selection",
  tag: "Role Selection",
  title: "Which best describes you?",
  subtitle: "Select your role to begin your tailored 10-question survey.",
  helperText: "Takes approximately 3 to 4 minutes. Your inputs will directly shape cloud compute and AI resources for your institution.",
  type: "single-choice",
  options: [
    {
      id: "student",
      label: "Student / Club Lead",
      sublabel: "Students, IEEE/ACM/GDSC leads, Hackathon participants & E-Cell members",
    },
    {
      id: "faculty",
      label: "HOD / Faculty",
      sublabel: "Department heads, professors, lab in-charges & project guides",
    },
    {
      id: "tpo",
      label: "Training & Placement Officer",
      sublabel: "Placement heads, coordinators & corporate relation officers",
    },
    {
      id: "admin",
      label: "Principal / Dean / Administrator",
      sublabel: "Principals, directors, deans & institutional decision makers",
    },
  ],
};

// SECTION D: Student / Club Lead Flow
export const STUDENT_QUESTIONS: QuestionDefinition[] = [
  {
    id: "D1",
    stepNumber: 1,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Context",
    title: "Which department are you studying in?",
    subtitle: "Every later question is asked in the context of this answer.",
    type: "single-choice",
    options: [
      { id: "CSE", label: "CSE" },
      { id: "AI & DS / AIML", label: "AI & DS / AIML" },
      { id: "IT", label: "IT" },
      { id: "ECE / EEE", label: "ECE / EEE" },
      { id: "Mechanical / Civil / Other", label: "Mechanical / Civil / Other" },
    ],
    linkReason: "Opening question. Every later question is asked in the context of this answer.",
    feedsDecision: "Lead tracker, tiering",
    getNextQuestionId: () => "D2",
  },
  {
    id: "D2",
    stepNumber: 2,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Context",
    title: "What kind of project have you done, or are you doing, in your department?",
    subtitle: "Tell us about the project domain or workload.",
    type: "single-choice",
    options: [
      { id: "AI / ML (vision, NLP, LLM chatbot, agents)", label: "AI / ML (vision, NLP, LLM chatbot, agents)" },
      { id: "Web or mobile app", label: "Web or mobile app" },
      { id: "IoT / embedded", label: "IoT / embedded" },
      { id: "Data analytics", label: "Data analytics" },
      { id: "Core-branch project", label: "Core-branch project" },
      { id: "Hackathon project only", label: "Hackathon project only" },
      { id: "No project yet", label: "No project yet" },
    ],
    linkReason: "Q1 told us the department, so we ask what that department's students actually build.",
    feedsDecision: "Workload profile",
    getNextQuestionId: (ans) => {
      if (ans === "No project yet") {
        return "D8"; // Skip directly to Q8 per PDF specification
      }
      return "D3";
    },
  },
  {
    id: "D3",
    stepNumber: 3,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Current State",
    title: "Is that project completed?",
    subtitle: "Help us understand the current stage of your project.",
    type: "single-choice",
    options: [
      { id: "Completed", label: "Completed" },
      { id: "Nearly done", label: "Nearly done" },
      { id: "Still ongoing", label: "Still ongoing" },
      { id: "Left it midway", label: "Left it midway" },
    ],
    linkReason: "Q2 named the project, so we now ask how it ended.",
    feedsDecision: "Completion rate",
    getNextQuestionId: () => "D4",
  },
  {
    id: "D4",
    stepNumber: 4,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Current State",
    title: (answers) => {
      const status = answers["D3"];
      if (status === "Completed" || status === "Nearly done") {
        return "How long did it take from starting to finishing?";
      }
      return "How long has it been so far (or how long since you started)?";
    },
    subtitle: "Select the closest timeframe.",
    type: "single-choice",
    options: [
      { id: "Under 2 weeks", label: "Under 2 weeks" },
      { id: "2 to 4 weeks", label: "2 to 4 weeks" },
      { id: "1 to 3 months", label: "1 to 3 months" },
      { id: "3 to 6 months", label: "3 to 6 months" },
      { id: "Over 6 months", label: "Over 6 months" },
    ],
    linkReason: "Q3 decided whether we measure a finished or an unfinished project.",
    feedsDecision: "Time-to-complete",
    getNextQuestionId: () => "D5",
  },
  {
    id: "D5",
    stepNumber: 5,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Pain Points",
    title: "Compared with your original plan, how did the timeline go?",
    subtitle: "Comparing actual execution against your initial plan.",
    type: "single-choice",
    options: [
      { id: "Finished early", label: "Finished early" },
      { id: "Finished on time", label: "Finished on time" },
      { id: "Slightly late (up to a month)", label: "Slightly late (up to a month)" },
      { id: "Very late", label: "Very late" },
      { id: "Never finished", label: "Never finished" },
    ],
    linkReason: "A duration means little on its own. Q4's number is now compared with what the student expected.",
    feedsDecision: "Delay severity",
    getNextQuestionId: () => "D6",
  },
  {
    id: "D6",
    stepNumber: 6,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Pain Points",
    title: (answers) => {
      const t = answers["D5"];
      if (t === "Finished early" || t === "Finished on time") {
        return "What helped you most? Pick up to 2.";
      }
      return "What slowed you down most? Pick up to 2.";
    },
    subtitle: "Select up to 2 key factors.",
    type: "multi-choice",
    maxSelections: 2,
    options: [
      { id: "Compute / GPU", label: "Compute / GPU" },
      { id: "Mentor or senior guidance", label: "Mentor or senior guidance" },
      { id: "Dataset", label: "Dataset" },
      { id: "Deployment", label: "Deployment" },
      { id: "Team coordination", label: "Team coordination" },
      { id: "Time and exams", label: "Time and exams" },
      { id: "Cost", label: "Cost" },
    ],
    linkReason: "Q5 separates students who struggled from those who did not, so we ask for the cause or the enabler.",
    feedsDecision: "Compute vs. mentorship",
    getNextQuestionId: () => "D7",
  },
  {
    id: "D7",
    stepNumber: 7,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Solution Fit",
    title: "How did you handle that?",
    subtitle: "If your top pick was compute, also tell us what you ran it on.",
    type: "composite",
    subQuestions: [
      {
        id: "handle_method",
        title: "How did you handle that obstacle or workflow?",
        type: "single-choice",
        options: [
          { id: "Asked seniors or friends", label: "Asked seniors or friends" },
          { id: "Online tutorials / YouTube", label: "Online tutorials / YouTube" },
          { id: "Free tools (Colab, Kaggle)", label: "Free tools (Colab, Kaggle)" },
          { id: "Paid for a tool or cloud", label: "Paid for a tool or cloud" },
          { id: "Asked faculty", label: "Asked faculty" },
          { id: "Reduced the project scope", label: "Reduced the project scope" },
          { id: "Gave up", label: "Gave up" },
        ],
        required: true,
      },
      {
        id: "compute_hardware",
        title: "If compute was an obstacle/factor: what did you run it on?",
        subtitle: "Optional if compute was not your main factor",
        type: "single-choice",
        options: [
          { id: "Laptop", label: "Laptop" },
          { id: "Colab / Kaggle", label: "Colab / Kaggle" },
          { id: "Paid cloud", label: "Paid cloud" },
          { id: "College GPU lab", label: "College GPU lab" },
        ],
        required: false,
      },
    ],
    linkReason: "Q6 named the obstacle; Q7 shows what students do about it today and how well it works.",
    feedsDecision: "Compute gap, current substitutes",
    getNextQuestionId: () => "D8",
  },
  {
    id: "D8",
    stepNumber: 8,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Solution Fit",
    title: "For your next project, which ONE free thing would help most?",
    subtitle: "Select the single most valuable resource for your upcoming work.",
    type: "single-choice",
    options: [
      { id: "Sponsored GPU credits", label: "Sponsored GPU credits" },
      { id: "Starter templates (RAG bot, AI agent)", label: "Starter templates (RAG bot, AI agent)" },
      { id: "Mentor office hours", label: "Mentor office hours" },
      { id: "Code review", label: "Code review" },
      { id: "Industry certificate", label: "Industry certificate" },
      { id: "Mock interviews", label: "Mock interviews" },
      { id: "Free workshop for our club", label: "Free workshop for our club" },
    ],
    linkReason: "Q7 showed a stopgap; Q8 asks what would replace it. Students with no project (Q2) enter here.",
    feedsDecision: "Top requested offering (KPI)",
    getNextQuestionId: () => "D9",
  },
  {
    id: "D9",
    stepNumber: 9,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Decision & Budget",
    title: "Would you pay for that, and how much per month?",
    subtitle: "Help us benchmark student-friendly pricing and subsidized tier structures.",
    type: "single-choice",
    options: [
      { id: "Nothing", label: "Nothing" },
      { id: "Under Rs. 300", label: "Under Rs. 300" },
      { id: "Rs. 300 to 1,000", label: "Rs. 300 to 1,000" },
      { id: "Rs. 1,000 to 3,000", label: "Rs. 1,000 to 3,000" },
      { id: "Above Rs. 3,000", label: "Above Rs. 3,000" },
      { id: "Only if there is a recognised certificate", label: "Only if there is a recognised certificate" },
    ],
    linkReason: "Q8 named the thing they want, so Q9 tests whether it is a want or a willing purchase.",
    feedsDecision: "Student willingness to pay",
    getNextQuestionId: () => "D10",
  },
  {
    id: "D10",
    stepNumber: 10,
    sectionCode: "D",
    sectionName: "Student / Club Lead",
    tag: "Commitment",
    title: "Can your club share this survey or host a 30-minute session, in exchange for a free workshop?",
    subtitle: "Connect with Kolaba Cloud AI for college workshops and campus ambassador programs.",
    type: "contact",
    subQuestions: [
      {
        id: "reach_channels",
        title: "How does your club reach students? (Select all that apply)",
        type: "multi-choice",
        options: [
          { id: "WhatsApp", label: "WhatsApp" },
          { id: "Instagram", label: "Instagram" },
          { id: "Discord", label: "Discord" },
          { id: "LinkedIn", label: "LinkedIn" },
          { id: "Class visits", label: "Class visits" },
        ],
        required: true,
      },
      {
        id: "club_size",
        title: "Club / Community Size",
        type: "single-choice",
        options: [
          { id: "Under 30", label: "Under 30" },
          { id: "30 to 100", label: "30 to 100" },
          { id: "Over 100", label: "Over 100" },
        ],
        required: true,
      },
      {
        id: "campus_ambassador",
        title: "Interested in becoming a Kolaba Campus Ambassador?",
        type: "single-choice",
        options: [
          { id: "Yes", label: "Yes" },
          { id: "Maybe", label: "Maybe" },
          { id: "No", label: "No" },
        ],
        required: true,
      },
      {
        id: "chapter",
        title: "Chapter / Organization Affiliation",
        type: "single-choice",
        options: [
          { id: "IEEE", label: "IEEE" },
          { id: "ACM", label: "ACM" },
          { id: "GDSC", label: "GDSC" },
          { id: "E-Cell", label: "E-Cell" },
          { id: "Other", label: "Other" },
          { id: "None", label: "None" },
        ],
        required: true,
      },
    ],
    linkReason: "After showing what they want and what they would pay, we ask whether they can spread it.",
    feedsDecision: "Ambassador seed, survey reach",
    getNextQuestionId: () => null,
  },
];

// SECTION B: HOD / Faculty Flow
export const FACULTY_QUESTIONS: QuestionDefinition[] = [
  {
    id: "B1",
    stepNumber: 1,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Context",
    title: "Which college, department and role do you have?",
    subtitle: "Tell us about your institution and academic role.",
    type: "composite",
    subQuestions: [
      {
        id: "college_name",
        title: "College / University Name",
        type: "text",
        placeholder: "e.g. RV College of Engineering, PES University",
        required: true,
      },
      {
        id: "city_state",
        title: "City, State",
        type: "text",
        placeholder: "e.g. Bengaluru, Karnataka",
        required: true,
      },
      {
        id: "department",
        title: "Department",
        type: "text",
        placeholder: "e.g. Computer Science & Engineering",
        required: true,
      },
      {
        id: "role",
        title: "Academic Role",
        type: "single-choice",
        options: [
          { id: "HOD", label: "HOD" },
          { id: "Professor", label: "Professor" },
          { id: "Associate/Assistant Professor", label: "Associate / Assistant Professor" },
          { id: "Lab in-charge", label: "Lab in-charge" },
          { id: "Project guide", label: "Project guide" },
        ],
        required: true,
      },
    ],
    linkReason: "Opening question. Everything else is about this department's students.",
    feedsDecision: "Lead tracker, persona",
    getNextQuestionId: () => "B2",
  },
  {
    id: "B2",
    stepNumber: 2,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Context",
    title: "Which project areas do your final-year students choose most?",
    subtitle: "Select all that apply for your department.",
    type: "multi-choice",
    options: [
      { id: "Machine learning", label: "Machine learning" },
      { id: "Deep learning / computer vision", label: "Deep learning / computer vision" },
      { id: "NLP / LLM chatbots", label: "NLP / LLM chatbots" },
      { id: "Data analytics", label: "Data analytics" },
      { id: "Web or mobile apps", label: "Web or mobile apps" },
      { id: "IoT / embedded", label: "IoT / embedded" },
      { id: "Core-branch projects", label: "Core-branch projects" },
    ],
    linkReason: "Q1 gave us the department; Q2 asks what its students build.",
    feedsDecision: "Workload profile",
    getNextQuestionId: () => "B3",
  },
  {
    id: "B3",
    stepNumber: 3,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Current State",
    title: "Of those projects, roughly what share finish on time?",
    subtitle: "Estimate the on-time completion percentage across final-year batches.",
    type: "single-choice",
    options: [
      { id: "Under 25%", label: "Under 25%" },
      { id: "25 to 50%", label: "25 to 50%" },
      { id: "50 to 75%", label: "50 to 75%" },
      { id: "Over 75%", label: "Over 75%" },
    ],
    linkReason: "Q2 listed the projects; Q3 asks how many actually get finished.",
    feedsDecision: "Completion rate",
    getNextQuestionId: () => "B4",
  },
  {
    id: "B4",
    stepNumber: 4,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Current State",
    title: "From topic approval to completion, how long does a typical project take?",
    subtitle: "Average timeline from proposal submission to final evaluation.",
    type: "single-choice",
    options: [
      { id: "Under 2 months", label: "Under 2 months" },
      { id: "2 to 4 months", label: "2 to 4 months" },
      { id: "4 to 6 months", label: "4 to 6 months" },
      { id: "Over 6 months, often spills into the next semester", label: "Over 6 months, often spills into the next semester" },
    ],
    linkReason: "Q3 gave the on-time rate; Q4 shows how long projects really run.",
    feedsDecision: "Time-to-complete",
    getNextQuestionId: () => "B5",
  },
  {
    id: "B5",
    stepNumber: 5,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Pain Points",
    title: (answers) => {
      const onTime = answers["B3"];
      const duration = answers["B4"];
      if (onTime === "Over 75%" && duration === "Under 2 months") {
        return "What makes projects work well here? Rank the top 3.";
      }
      return "What is the main reason projects run late or fail? Rank the top 3.";
    },
    subtitle: "Select and order your top 3 factors (1st = most significant).",
    type: "ranking",
    maxSelections: 3,
    options: [
      { id: "GPU / compute access", label: "GPU / compute access" },
      { id: "Mentorship", label: "Mentorship" },
      { id: "Real-world problem statements", label: "Real-world problem statements" },
      { id: "Datasets", label: "Datasets" },
      { id: "Deployment skills", label: "Deployment skills" },
      { id: "Student time and workload", label: "Student time and workload" },
    ],
    linkReason: "Q4 showed delay; Q5 asks why. If projects run smoothly, we learn what already works.",
    feedsDecision: "Compute vs. mentorship",
    getNextQuestionId: () => "B6",
  },
  {
    id: "B6",
    stepNumber: 6,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Pain Points",
    title: "How do students currently work around that problem?",
    subtitle: "Select all workarounds and stopgaps used by students.",
    type: "multi-choice",
    options: [
      { id: "Personal laptops", label: "Personal laptops" },
      { id: "Free cloud tiers (Colab, Kaggle)", label: "Free cloud tiers (Colab, Kaggle)" },
      { id: "Paid cloud, self-funded", label: "Paid cloud, self-funded" },
      { id: "College GPU lab", label: "College GPU lab" },
      { id: "Senior students", label: "Senior students" },
      { id: "Online courses", label: "Online courses" },
      { id: "They reduce project scope", label: "They reduce project scope" },
    ],
    linkReason: "Q5 named the cause; Q6 shows the stopgaps students use and the quality they get.",
    feedsDecision: "Cloud credits demand",
    getNextQuestionId: () => "B7",
  },
  {
    id: "B7",
    stepNumber: 7,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Solution Fit",
    title: "Can you and your colleagues guide students on hands-on GenAI, AI infrastructure, Cloud and IOT projects?",
    subtitle: "Assess faculty comfort level and most effective upskilling formats.",
    type: "composite",
    subQuestions: [
      {
        id: "faculty_comfort",
        title: "Faculty comfort level in guiding hands-on GenAI, AI infrastructure, Cloud and IOT projects:",
        type: "scale",
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: "1 = Very low", max: "5 = Very high" },
        required: true,
      },
      {
        id: "fdp_preference",
        title: "What faculty development format would help most?",
        type: "single-choice",
        options: [
          { id: "One-week FDP", label: "One-week FDP" },
          { id: "Weekend workshops", label: "Weekend workshops" },
          { id: "Self-paced online", label: "Self-paced online" },
          { id: "Co-teaching with industry", label: "Co-teaching with industry" },
          { id: "Ready-made lab modules", label: "Ready-made lab modules" },
        ],
        required: true,
      },
    ],
    linkReason: "Q6 showed students fending for themselves; Q7 asks whether faculty can fill the gap.",
    feedsDecision: "FDP demand",
    getNextQuestionId: () => "B8",
  },
  {
    id: "B8",
    stepNumber: 8,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Solution Fit",
    title: "Which single support would best fix the main problem from Q5?",
    subtitle: "Identify the top offering and preferred institutional model.",
    type: "composite",
    subQuestions: [
      {
        id: "primary_support",
        title: "Which single support would best fix the main issue?",
        type: "single-choice",
        options: [
          { id: "Cloud GPU credits", label: "Cloud GPU credits" },
          { id: "On-campus GPU workstations", label: "On-campus GPU workstations" },
          { id: "Lab sandbox with curriculum modules", label: "Lab sandbox with curriculum modules" },
          { id: "Mentorship and code review", label: "Mentorship and code review" },
          { id: "Industry certification", label: "Industry certification" },
          { id: "Faculty training", label: "Faculty training" },
        ],
        required: true,
      },
      {
        id: "preferred_model",
        title: "Preferred institutional model:",
        type: "single-choice",
        options: [
          { id: "Own the hardware", label: "Own the hardware" },
          { id: "Subscribe", label: "Subscribe" },
          { id: "Sponsored by industry", label: "Sponsored by industry" },
        ],
        required: true,
      },
    ],
    linkReason: "Q5 to Q7 built the case: the cause, the stopgap, the faculty gap. Q8 asks for one fix and how to pay for it.",
    feedsDecision: "Top offering, capex vs. opex (KPI)",
    getNextQuestionId: () => "B9",
  },
  {
    id: "B9",
    stepNumber: 9,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Decision & Budget",
    title: "Who decides on adopting that support, and what proof would you need?",
    subtitle: "Key decision makers and evidentiary requirements.",
    type: "composite",
    subQuestions: [
      {
        id: "decider",
        title: "Primary decision maker for adopting support:",
        type: "single-choice",
        options: [
          { id: "Me", label: "Me" },
          { id: "HOD", label: "HOD" },
          { id: "Principal", label: "Principal" },
          { id: "TPO", label: "TPO" },
          { id: "Committee", label: "Committee" },
        ],
        required: true,
      },
      {
        id: "proof_needed",
        title: "Proof / documentation required before approval (Select all that apply):",
        type: "multi-choice",
        options: [
          { id: "Pilot results", label: "Pilot results" },
          { id: "Mapping to university syllabus", label: "Mapping to university syllabus" },
          { id: "Data privacy", label: "Data privacy" },
          { id: "Ease of use", label: "Ease of use" },
          { id: "Low cost", label: "Low cost" },
          { id: "Certification value", label: "Certification value" },
        ],
        required: true,
      },
    ],
    linkReason: "Q8 named the fix; Q9 asks who can say yes and what evidence they want.",
    feedsDecision: "Persona controlling adoption",
    getNextQuestionId: () => "B10",
  },
  {
    id: "B10",
    stepNumber: 10,
    sectionCode: "B",
    sectionName: "HOD / Faculty",
    tag: "Commitment",
    title: "Would you run a pilot with a final-year batch (about 10 to 30 students) or host a workshop?",
    subtitle: "Partner with Kolaba Cloud AI for pilot cohorts and faculty workshops.",
    type: "contact",
    subQuestions: [
      {
        id: "pilot_interest",
        title: "Select your interest (Select all that apply):",
        type: "multi-choice",
        options: [
          { id: "Pilot with a project batch", label: "Pilot with a project batch" },
          { id: "Host a faculty workshop", label: "Host a faculty workshop" },
          { id: "Host a student info session", label: "Host a student info session" },
          { id: "Not right now", label: "Not right now" },
        ],
        required: true,
      },
    ],
    linkReason: "Q9 gave the proof they need; Q10 offers a pilot that produces it.",
    feedsDecision: "Pilot-ready list, discovery calls",
    getNextQuestionId: () => null,
  },
];

// SECTION C: Training & Placement Officer (TPO) Flow
export const TPO_QUESTIONS: QuestionDefinition[] = [
  {
    id: "C1",
    stepNumber: 1,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Context",
    title: "Which college is this, and how big is your CS/AI final-year batch?",
    subtitle: "Tell us about your institution and student placement batch size.",
    type: "composite",
    subQuestions: [
      {
        id: "college_name",
        title: "College Name & City/State",
        type: "text",
        placeholder: "e.g. BMS College of Engineering, Bengaluru",
        required: true,
      },
      {
        id: "batch_size",
        title: "CS / AI final-year batch size:",
        type: "single-choice",
        options: [
          { id: "Under 60", label: "Under 60" },
          { id: "60 to 120", label: "60 to 120" },
          { id: "120 to 250", label: "120 to 250" },
          { id: "Over 250", label: "Over 250" },
        ],
        required: true,
      },
    ],
    linkReason: "Opening question. Batch size sets the scale for everything that follows.",
    feedsDecision: "Lead tracker, sizing",
    getNextQuestionId: () => "C2",
  },
  {
    id: "C2",
    stepNumber: 2,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Current State",
    title: "Last year, roughly what share of that batch was placed in tech roles?",
    subtitle: "Estimated tech placement percentage from the most recent graduating batch.",
    type: "single-choice",
    options: [
      { id: "Under 20%", label: "Under 20%" },
      { id: "20 to 40%", label: "20 to 40%" },
      { id: "40 to 60%", label: "40 to 60%" },
      { id: "60 to 80%", label: "60 to 80%" },
      { id: "Over 80%", label: "Over 80%" },
      { id: "Not sure", label: "Not sure" },
    ],
    linkReason: "Q1 gave the batch; Q2 says how many were placed.",
    feedsDecision: "Placement baseline",
    getNextQuestionId: () => "C3",
  },
  {
    id: "C3",
    stepNumber: 3,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Current State",
    title: "Which kinds of recruiters hired those students?",
    subtitle: "Select all types of hiring organizations.",
    type: "multi-choice",
    options: [
      { id: "IT services", label: "IT services" },
      { id: "Product companies", label: "Product companies" },
      { id: "Startups", label: "Startups" },
      { id: "Global capability centres", label: "Global capability centres (GCCs)" },
      { id: "Banking / financial services", label: "Banking / financial services" },
      { id: "Core engineering", label: "Core engineering" },
      { id: "AI-focused firms", label: "AI-focused firms" },
    ],
    linkReason: "Q2 counted the placed students; Q3 says who hired them.",
    feedsDecision: "Recruiter mix",
    getNextQuestionId: () => "C4",
  },
  {
    id: "C4",
    stepNumber: 4,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Pain Points",
    title: "What did those recruiters most often say was missing in your students? (up to 3)",
    subtitle: "Pick up to 3 common gap areas highlighted by interviewers.",
    type: "multi-choice",
    maxSelections: 3,
    options: [
      {
        id: "Lack of knowledge on AI infrastructure, Cloud technologies, IOT projects",
        label: "Lack of knowledge on  AI infrastructure, Cloud technologies, IOT projects",
      },
      {
        id: "Lack of hands of experience into real world industry project samples / internship",
        label: "Lack of hands of experience into real world industry project samples / internship",
      },
      {
        id: "Lack practice and access to GPU infra / Gen AI LLM exposure / IOT full stack development",
        label: "Lack practice and access to GPU infra / Gen AI LLM exposure / IOT full stack development",
      },
    ],
    hasObservationText: true,
    observationLabel: "Mention if others:",
    observationPlaceholder: "Mention if others...",
    linkReason: "Q3 named the recruiters; Q4 asks what feedback they gave.",
    feedsDecision: "Gap validation",
    getNextQuestionId: () => "C5",
  },
  {
    id: "C5",
    stepNumber: 5,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Pain Points",
    title: "How much do students' final-year projects help them in technical interviews?",
    subtitle: "Evaluate the direct impact of capstone projects during campus placements.",
    type: "composite",
    subQuestions: [
      {
        id: "project_interview_value",
        title: "Impact on technical interviews:",
        type: "scale",
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: "1 = Hardly at all", max: "5 = A major advantage" },
        required: true,
      },
      {
        id: "recruiters_ask_frequency",
        title: "Do recruiters ask in-depth questions about projects?",
        type: "single-choice",
        options: [
          { id: "Always", label: "Always" },
          { id: "Often", label: "Often" },
          { id: "Rarely", label: "Rarely" },
          { id: "Never", label: "Never" },
        ],
        required: true,
      },
    ],
    linkReason: "Q4 gave the gap; Q5 checks whether projects are where it shows.",
    feedsDecision: "Project-track hypothesis",
    getNextQuestionId: () => "C6",
  },
  {
    id: "C6",
    stepNumber: 6,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Pain Points",
    title: "How do you currently showcase student projects to recruiters?",
    subtitle: "Current format for highlighting student engineering talent.",
    type: "single-choice",
    options: [
      { id: "Nothing formal", label: "Nothing formal" },
      { id: "Internal project expo", label: "Internal project expo" },
      { id: "Hackathon results", label: "Hackathon results" },
      { id: "External certifications", label: "External certifications" },
      { id: "Recruiter-led demo day", label: "Recruiter-led demo day" },
      { id: "Other", label: "Other" },
    ],
    linkReason: "Q5 asked how projects perform; Q6 asks how they are presented.",
    feedsDecision: "Demo day / talent pipeline",
    getNextQuestionId: () => "C7",
  },
  {
    id: "C7",
    stepNumber: 7,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Solution Fit",
    title: "Which would best close the gap from Q4? Rank your top 3.",
    subtitle: "Rank the top 3 interventions to boost recruiter hire rates (1st = most effective).",
    type: "ranking",
    maxSelections: 3,
    options: [
      { id: "Mentored, industry-style project track", label: "Mentored, industry-style project track" },
      { id: "Co-branded certificate", label: "Co-branded certificate" },
      { id: "Mock interviews", label: "Mock interviews" },
      { id: "Demo day with hiring partners", label: "Demo day with hiring partners" },
      { id: "AI skills bootcamp", label: "AI skills bootcamp" },
      { id: "Resume and portfolio reviews", label: "Resume and portfolio reviews" },
    ],
    linkReason: "Q4 to Q6 showed the gap, the interview impact and the current showcase. Q7 asks what would fix it.",
    feedsDecision: "Top requested offering (KPI)",
    getNextQuestionId: () => "C8",
  },
  {
    id: "C8",
    stepNumber: 8,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Solution Fit",
    title: "If your #1 choice existed, who should pay and what is reasonable per student?",
    subtitle: "Cost distribution and pricing viability per enrolled student.",
    type: "composite",
    subQuestions: [
      {
        id: "funding_source",
        title: "Who should fund this program?",
        type: "single-choice",
        options: [
          { id: "College", label: "College" },
          { id: "Students", label: "Students" },
          { id: "Industry-sponsored", label: "Industry-sponsored" },
          { id: "Shared", label: "Shared" },
        ],
        required: true,
      },
      {
        id: "cost_per_student",
        title: "What is a reasonable cost per student?",
        type: "single-choice",
        options: [
          { id: "Free only", label: "Free only" },
          { id: "Up to Rs. 500", label: "Up to Rs. 500" },
          { id: "Rs. 500 to 2,000", label: "Rs. 500 to 2,000" },
          { id: "Rs. 2,000 to 5,000", label: "Rs. 2,000 to 5,000" },
          { id: "Above Rs. 5,000", label: "Above Rs. 5,000" },
        ],
        required: true,
      },
    ],
    linkReason: "Q7 picked the solution; Q8 tests whether anyone would pay for it.",
    feedsDecision: "Willingness to pay",
    getNextQuestionId: () => "C9",
  },
  {
    id: "C9",
    stepNumber: 9,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Decision & Budget",
    title: "Who approves such a program and how long does it take?",
    subtitle: "Approval authority and decision timeline.",
    type: "composite",
    subQuestions: [
      {
        id: "approver",
        title: "Program Approver:",
        type: "single-choice",
        options: [
          { id: "TPO alone", label: "TPO alone" },
          { id: "TPO with Principal", label: "TPO with Principal" },
          { id: "Placement committee", label: "Placement committee" },
          { id: "Management", label: "Management" },
        ],
        required: true,
      },
      {
        id: "approval_timeline",
        title: "Typical approval turnaround time:",
        type: "single-choice",
        options: [
          { id: "Under 1 month", label: "Under 1 month" },
          { id: "1 to 3 months", label: "1 to 3 months" },
          { id: "3 to 6 months", label: "3 to 6 months" },
          { id: "Over 6 months", label: "Over 6 months" },
        ],
        required: true,
      },
    ],
    linkReason: "Q8 named the payer; Q9 asks who signs and how soon.",
    feedsDecision: "Budget authority, sales cycle",
    getNextQuestionId: () => "C10",
  },
  {
    id: "C10",
    stepNumber: 10,
    sectionCode: "C",
    sectionName: "Training & Placement Officer",
    tag: "Commitment",
    title: "Would you host a free pilot cohort or a recruiter demo day with Kolaba?",
    subtitle: "Explore placement partnership opportunities with Kolaba Cloud AI.",
    type: "contact",
    subQuestions: [
      {
        id: "tpo_pilot_interest",
        title: "Select preferred collaboration models (Select all that apply):",
        type: "multi-choice",
        options: [
          { id: "Free pilot project cohort", label: "Free pilot project cohort" },
          { id: "Demo day", label: "Demo day" },
          { id: "Mock interview sessions", label: "Mock interview sessions" },
          { id: "Not right now", label: "Not right now" },
        ],
        required: true,
      },
    ],
    linkReason: "Q9 gave the approval path; Q10 offers a first step that fits it.",
    feedsDecision: "Pilot-ready list, hiring pipeline",
    getNextQuestionId: () => null,
  },
];

// SECTION A: Principal / Dean / Administrator Flow
export const ADMIN_QUESTIONS: QuestionDefinition[] = [
  {
    id: "A1",
    stepNumber: 1,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Context",
    title: "Please tell us about your institution.",
    subtitle: "Institutional profile and active technical departments.",
    type: "composite",
    subQuestions: [
      {
        id: "college_details",
        title: "College Name & City/State",
        type: "text",
        placeholder: "e.g. National Institute of Technology, Surathkal",
        required: true,
      },
      {
        id: "institution_type",
        title: "Institution Type:",
        type: "single-choice",
        options: [
          { id: "Government", label: "Government" },
          { id: "Government-aided", label: "Government-aided" },
          { id: "Private", label: "Private" },
          { id: "Autonomous", label: "Autonomous" },
          { id: "Deemed university", label: "Deemed university" },
        ],
        required: true,
      },
      {
        id: "branches_offered",
        title: "Branches Offered (Select all that apply):",
        type: "multi-choice",
        options: [
          { id: "CSE", label: "CSE" },
          { id: "AI & DS", label: "AI & DS" },
          { id: "AIML", label: "AIML" },
          { id: "IT", label: "IT" },
          { id: "ECE/EEE", label: "ECE / EEE" },
          { id: "Other", label: "Other" },
        ],
        required: true,
      },
    ],
    linkReason: "Opening question. It also tiers the college for the lead tracker.",
    feedsDecision: "Lead tracker, tiering",
    getNextQuestionId: () => "A2",
  },
  {
    id: "A2",
    stepNumber: 2,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Context",
    title: "In the branches you listed, roughly how many final-year students do AI/ML projects each year?",
    subtitle: "Estimated student volume and project domains in your institution.",
    type: "composite",
    subQuestions: [
      {
        id: "student_volume",
        title: "Roughly how many final-year students do AI/ML projects each year?",
        type: "single-choice",
        options: [
          { id: "Under 30", label: "Under 30" },
          { id: "30 to 100", label: "30 to 100" },
          { id: "100 to 250", label: "100 to 250" },
          { id: "Over 250", label: "Over 250" },
          { id: "None yet", label: "None yet" },
        ],
        required: true,
      },
      {
        id: "project_types",
        title: "What kinds of projects do students do in your institution? (Select all that apply):",
        type: "multi-choice",
        options: [
          { id: "Real industry-based AI Infrastructure projects", label: "Real industry-based AI Infrastructure projects" },
          { id: "Cloud Projects", label: "Cloud Projects" },
          { id: "Generative AI/LLM projects", label: "Generative AI/LLM projects" },
          { id: "IOT projects", label: "IOT projects" },
        ],
        required: true,
      },
      {
        id: "observation",
        title: "Observation / Requirement on Projects:",
        type: "textarea",
        placeholder: "Write your observation or requirement...",
        required: false,
      },
    ],
    linkReason: "Q1 listed the branches; Q2 sizes how many students work on AI and what domains they cover.",
    feedsDecision: "Market size and project domain demand",
    getNextQuestionId: () => "A3",
  },
  {
    id: "A3",
    stepNumber: 3,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Current State",
    title: "What cloud infrastructure and storage options do students use for projects and data workflows?",
    subtitle: "Tell us about cloud compute and storage options in use.",
    type: "composite",
    subQuestions: [
      {
        id: "cloud_infra",
        title: "Cloud infrastructure in use:",
        type: "single-choice",
        options: [
          { id: "Dedicated GPU lab", label: "Dedicated GPU lab" },
          { id: "A few GPU machines shared across departments", label: "A few GPU machines shared across departments" },
          { id: "CPU-only labs", label: "CPU-only labs" },
          { id: "Free or paid cloud", label: "Free or paid cloud" },
          { id: "None", label: "None" },
        ],
        required: true,
      },
      {
        id: "cloud_infra_observation",
        title: "Observation / Requirement on Cloud Infrastructure:",
        type: "textarea",
        placeholder: "Write your observation or requirement on cloud infrastructure...",
        required: false,
      },
      {
        id: "storage_options",
        title: "Storage option for projects and data workflows:",
        type: "single-choice",
        options: [
          { id: "High-Performance NVMe/SSD Storage", label: "High-Performance NVMe/SSD Storage" },
          { id: "Cloud Object Storage (S3 / Cloud Buckets)", label: "Cloud Object Storage (S3 / Cloud Buckets)" },
          { id: "Network Attached Storage (NAS)", label: "Network Attached Storage (NAS)" },
          { id: "Local PC / Workstation Storage", label: "Local PC / Workstation Storage" },
          { id: "None / Other", label: "None / Other" },
        ],
        required: true,
      },
      {
        id: "storage_observation",
        title: "Observation / Requirement on Storage Options:",
        type: "textarea",
        placeholder: "Write your observation or requirement on storage...",
        required: false,
      },
    ],
    linkReason: "Q2 counted the students; Q3 says what they run their work on.",
    feedsDecision: "Cloud vs. workstation need",
    getNextQuestionId: () => "A4",
  },
  {
    id: "A4",
    stepNumber: 4,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Current State",
    title: "Is that enough for those students?",
    subtitle: "Evaluating institutional compute sufficiency and potential bottlenecks.",
    type: "composite",
    subQuestions: [
      {
        id: "compute_sufficiency_score",
        title: "Sufficiency rating:",
        type: "scale",
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: "1 = Not at all", max: "5 = More than enough" },
        required: true,
      },
      {
        id: "biggest_shortfall",
        title: "What is the biggest shortfall?",
        subtitle: "Appears if sufficiency rating is 1, 2, or 3",
        type: "single-choice",
        options: [
          { id: "Capacity", label: "Capacity" },
          { id: "Speed", label: "Speed" },
          { id: "Access hours", label: "Access hours" },
          { id: "Software", label: "Software" },
          { id: "Support", label: "Support" },
        ],
        condition: (ans) => {
          const s = ans["compute_sufficiency_score"];
          return s !== undefined && Number(s) <= 3;
        },
        required: false,
      },
    ],
    linkReason: "Q3 named the setup; Q4 judges it.",
    feedsDecision: "Gap intensity",
    getNextQuestionId: () => "A5",
  },
  {
    id: "A5",
    stepNumber: 5,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Pain Points",
    title: (answers) => {
      const score = answers["A4"]?.compute_sufficiency_score;
      if (score && Number(score) >= 4) {
        return "What is limiting further growth? (select up to 3)";
      }
      return "What has held back upgrading? (select up to 3)";
    },
    subtitle: "Select up to 3 principal organizational or budget hurdles.",
    type: "multi-choice",
    maxSelections: 3,
    options: [
      { id: "Capex / budget", label: "Capex / budget" },
      { id: "Procurement delays", label: "Procurement delays" },
      { id: "No staff to maintain hardware", label: "No staff to maintain hardware" },
      { id: "Power, cooling or space", label: "Power, cooling or space" },
      { id: "Unclear return on investment", label: "Unclear return on investment" },
      { id: "Faculty lack GenAI expertise", label: "Faculty lack GenAI expertise" },
      { id: "Not planning to upgrade", label: "Not planning to upgrade" },
    ],
    linkReason: "Q4 found a shortfall; Q5 explains why it persists.",
    feedsDecision: "Offering fit: cloud vs. on-prem",
    getNextQuestionId: () => "A6",
  },
  {
    id: "A6",
    stepNumber: 6,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Pain Points",
    title: "Which outcome does this gap hurt most for the institution? Rank the top 3.",
    subtitle: "Select and rank the top 3 institutional metrics impacted (1st = greatest impact).",
    type: "ranking",
    maxSelections: 3,
    options: [
      { id: "NBA / NAAC accreditation evidence", label: "NBA / NAAC accreditation evidence" },
      { id: "NIRF ranking", label: "NIRF ranking" },
      { id: "Placement outcomes", label: "Placement outcomes" },
      { id: "Research output", label: "Research output" },
      { id: "Industry partnerships", label: "Industry partnerships" },
      { id: "Admissions and enrolment demand", label: "Admissions and enrolment demand" },
    ],
    linkReason: "Q5 gave the barrier; Q6 links it to what leadership is judged on.",
    feedsDecision: "Messaging",
    getNextQuestionId: () => "A7",
  },
  {
    id: "A7",
    stepNumber: 7,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Solution Fit",
    title: "Which responsibility / solution would you consider first to improve that outcome?",
    subtitle: "Select the most attractive institutional responsibility or solution model.",
    type: "single-choice",
    options: [
      { id: "Cloud GPU credits for student projects", label: "Cloud GPU credits for student projects" },
      { id: "On-campus AI lab (workstations plus software)", label: "On-campus AI lab (workstations plus software)" },
      { id: "Faculty development programme on GenAI", label: "Faculty development programme on GenAI" },
      { id: "Student mentorship and certification", label: "Student mentorship and certification" },
      { id: "Hackathon / hiring demo day", label: "Hackathon / hiring demo day" },
      { id: "AI Centre of Excellence with an MoU and joint case study", label: "AI Centre of Excellence with an MoU and joint case study" },
      { id: "None", label: "None" },
    ],
    hasObservationText: true,
    observationLabel: "Observation / Requirement:",
    observationPlaceholder: "Write your observation or requirement...",
    linkReason: "Q6 named the outcome; Q7 asks which offering would move it.",
    feedsDecision: "Top requested offering (KPI)",
    getNextQuestionId: () => "A8",
  },
  {
    id: "A8",
    stepNumber: 8,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Solution Fit",
    title: "If student work ran on that platform, where must the data stay?",
    subtitle: "Institutional data residency and compliance guidelines.",
    type: "single-choice",
    options: [
      { id: "On campus only", label: "On campus only" },
      { id: "Private cloud / VPC inside India", label: "Private cloud / VPC inside India" },
      { id: "Any Indian cloud region", label: "Any Indian cloud region" },
      { id: "No restriction", label: "No restriction" },
    ],
    linkReason: "Q7 chose a platform; Q8 raises the data question that comes with it.",
    feedsDecision: "Private-infra proof point",
    getNextQuestionId: () => "A9",
  },
  {
    id: "A9",
    stepNumber: 9,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Decision & Budget",
    title: "Who approves this kind of responsibility / solution, how long does it take, and is budget set aside?",
    subtitle: "Decision governance and budget allocation details.",
    type: "composite",
    subQuestions: [
      {
        id: "approver",
        title: "Approving Authority:",
        type: "single-choice",
        options: [
          { id: "Principal/Director", label: "Principal / Director" },
          { id: "Management/Trust", label: "Management / Trust" },
          { id: "HOD", label: "HOD" },
          { id: "Committee", label: "Committee" },
          { id: "Government/university", label: "Government / University" },
        ],
        required: true,
      },
      {
        id: "procurement_timeline",
        title: "Procurement / Approval Timeline:",
        type: "single-choice",
        options: [
          { id: "Under 1 month", label: "Under 1 month" },
          { id: "1 to 3 months", label: "1 to 3 months" },
          { id: "3 to 6 months", label: "3 to 6 months" },
          { id: "Over 6 months", label: "Over 6 months" },
          { id: "Tender/GeM", label: "Tender / GeM" },
        ],
        required: true,
      },
      {
        id: "budget_set_aside",
        title: "Is budget set aside this year?",
        type: "single-choice",
        options: [
          { id: "Yes", label: "Yes" },
          { id: "No", label: "No" },
          { id: "Not sure", label: "Not sure" },
        ],
        required: true,
      },
      {
        id: "budget_range",
        title: "Budget Range (if set aside):",
        type: "single-choice",
        options: [
          { id: "Under Rs. 5 lakh", label: "Under Rs. 5 lakh" },
          { id: "5 to 15 lakh", label: "Rs. 5 to 15 lakh" },
          { id: "15 to 50 lakh", label: "Rs. 15 to 50 lakh" },
          { id: "Above 50 lakh", label: "Above Rs. 50 lakh" },
          { id: "Prefer not to say", label: "Prefer not to say" },
        ],
        condition: (ans) => ans["budget_set_aside"] === "Yes",
        required: false,
      },
    ],
    linkReason: "Q8 settled the technical conditions; Q9 asks who signs, how soon and with what money.",
    feedsDecision: "Budget authority, willingness to pay",
    getNextQuestionId: () => "A10",
  },
  {
    id: "A10",
    stepNumber: 10,
    sectionCode: "A",
    sectionName: "Principal / Dean / Administrator",
    tag: "Commitment",
    title: "Would you welcome a free, capped pilot of that responsibility / solution, in exchange for feedback and a joint case study?",
    subtitle: "Launch a pilot cohort with Kolaba Cloud AI for your college.",
    type: "contact",
    subQuestions: [
      {
        id: "pilot_welcome",
        title: "Pilot interest:",
        type: "single-choice",
        options: [
          { id: "Yes", label: "Yes" },
          { id: "Maybe, please call me", label: "Maybe, please call me" },
          { id: "No", label: "No" },
        ],
        required: true,
      },
    ],
    linkReason: "Q9 gave the approval path; Q10 offers a low-risk first step.",
    feedsDecision: "Pilot-ready list (5 to 10)",
    getNextQuestionId: () => null,
  },
];

export const FLOWS_BY_PERSONA: Record<RespondentType, QuestionDefinition[]> = {
  student: STUDENT_QUESTIONS,
  faculty: FACULTY_QUESTIONS,
  tpo: TPO_QUESTIONS,
  admin: ADMIN_QUESTIONS,
};

export const PERSONA_INFO = {
  student: {
    label: "Student / Club Lead",
    flowName: "Section D: Student / Club Lead Flow",
    description: "For students, hackathon leads, club captains and AI enthusiasts.",
    badge: "Student Survey",
    icon: "GraduationCap",
    totalSteps: 10,
  },
  faculty: {
    label: "HOD / Faculty",
    flowName: "Section B: HOD / Faculty Flow",
    description: "For department heads, professors, lab in-charges and project guides.",
    badge: "Faculty Survey",
    icon: "BookOpen",
    totalSteps: 10,
  },
  tpo: {
    label: "Training & Placement Officer",
    flowName: "Section C: Training & Placement Officer Flow",
    description: "For placement directors, TPOs, coordinators and corporate liaisons.",
    badge: "TPO Survey",
    icon: "Briefcase",
    totalSteps: 10,
  },
  admin: {
    label: "Principal / Dean / Administrator",
    flowName: "Section A: Principal / Dean / Administrator Flow",
    description: "For institutional leaders, principals, deans and board members.",
    badge: "Leadership Survey",
    icon: "Building2",
    totalSteps: 10,
  },
};

export const CONSENT_STATEMENT =
  "I agree that Kolaba Cloud AI may contact me about this survey and a possible pilot, and store my responses for this research.";

export const SURVEY_INTRO_TEXT =
  "Kolaba Cloud AI, a Bengaluru-based enterprise AI company, is talking to engineering colleges across India before building anything for them. We want to understand where GPU access, mentorship, faculty training or placement support would genuinely help. This takes about 3 to 4 minutes. We are not selling anything with this form. Your answers are used only for this research and any follow-up you agree to.";
